"""empty message

Revision ID: 11a3b73d50b2
Revises: dcc54716850f
Create Date: 2020-06-04 12:34:26.788767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11a3b73d50b2'
down_revision = 'dcc54716850f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('favorite_colors', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'favorite_colors')
    # ### end Alembic commands ###
